### ISSUE TITLE
Defaults for parallel compile and link jobs

### ISSUE THREAD

**Issue by dileks** [ClangBuiltLinux/tc-build#137]
With https://github.com/ClangBuiltLinux/tc-build/commit/f917c5c2adb5a7b2e18e592f6725399aed357952 you introduced custom options for parrallel compile and link jobs.
I welcome this, thanks.

When I first had issues with compiling/linking a llvm-toolchain LLVM folks recommended to use safe settings:
`parallel compile jobs = 2` and ... safe `parallel link jobs = 1`.
Cannot say what the default is for linking in tc-build or LLVM upstream, but I see `parallel compile jobs` are set to `4` (maximum of available CPUs?) in tc-build for my Intel SandyBridge notebook.
What are the default settings?

Please note @nickdesaulniers tip in the below link.

[1] https://github.com/ClangBuiltLinux/llvm-dev-conf-2020/issues/3#issuecomment-704398983

**Comment by nathanchance** [comment]
There is no default value of `LLVM_PARALLEL_COMPILE_JOBS` or `LLVM_PARALLEL_LINK_JOBS`:

https://github.com/llvm/llvm-project/blob/c37dd3b6d553d7ae3afaf677f1c6abdf6b1ec74e/llvm/cmake/modules/HandleLLVMOptions.cmake#L26-L52

https://llvm.org/docs/CMake.html#llvm-specific-variables

tc-build does not touch that value. I do not know what `ninja`'s default parallelism but they do not recommend setting a `-j` value so it seems like they have their own heuristic.

**Comment by dileks** [comment]
OK, I see that commit was for custom cmake options passing to tc-build.

**Comment by msfjarvis** [comment]
I suppose this is resolved then? Closing.

**Comment by dileks** [comment]
IMHO - not really resolved.

I rebuild with safe parallel jobs setting for compile (=2) and link (=1).
It increased my build-time from usually 03:15 to 03:25 (mm:ss) - means 10 minutes.

The initial (Chinese) reporter was building with tc-build on an embedded system and had failures.

We should be user-friendly and offer/set safe settings.

My €0,02.

**Comment by nathanchance** [comment]
Building on a phone versus building on a laptop or server are two completely different use cases. The script aims to be as quick as possible which means building with as many compile and link jobs as ninja feels is reasonable by default. The `-D` option is there if it needs to be lowered but I disagree with setting any value to those options by default, especially given that LLVM doesn't.

**Comment by dileks** [comment]
One question:

When I pass compile/link jobs options and do a thinlto+pgo build - is that passed to stage2 and stage3?

**Comment by nathanchance** [comment]
Yes, custom values are passed to all cmake invocations.

**Comment by dileks** [comment]
Thanks.

I dropped my compile and link jobs options. Will only add link jobs = 1.
For the rest I trust NinJA. Ja means German Yes.

Nathan Chancellor <notifications@github.com> schrieb am Di., 2. Feb. 2021,
08:26:
